USE [master]
GO

/****** 物件:  Database [MidnightECPlant]    指令碼日期: 2026/9/5 下午 10:57:52 ******/
CREATE DATABASE [MidnightECPlant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MidnightECPlant', FILENAME = N'D:\SQL Server\DATA\MidnightECPlant.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MidnightECPlant_log', FILENAME = N'D:\SQL Server\DATA\MidnightECPlant_log.ldf' , SIZE = 8192KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MidnightECPlant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MidnightECPlant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ARITHABORT OFF 
GO

ALTER DATABASE [MidnightECPlant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MidnightECPlant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MidnightECPlant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MidnightECPlant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MidnightECPlant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MidnightECPlant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MidnightECPlant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MidnightECPlant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MidnightECPlant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MidnightECPlant] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MidnightECPlant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MidnightECPlant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MidnightECPlant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MidnightECPlant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MidnightECPlant] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MidnightECPlant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MidnightECPlant] SET RECOVERY FULL 
GO

ALTER DATABASE [MidnightECPlant] SET  MULTI_USER 
GO

ALTER DATABASE [MidnightECPlant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MidnightECPlant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MidnightECPlant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MidnightECPlant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MidnightECPlant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MidnightECPlant] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [MidnightECPlant] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MidnightECPlant] SET QUERY_STORE = ON
GO

ALTER DATABASE [MidnightECPlant] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MidnightECPlant] SET  READ_WRITE 
GO


