<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>midnight-ec-plant-web-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Midnight.EC.Plant.WEB.Services\Midnight.EC.Plant.WEB.Services.csproj" />
  </ItemGroup>

</Project>
