// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Midnight.EC.Plant.WEB.Models.Data;

#nullable disable

namespace Midnight.EC.Plant.WEB.Models.Migrations
{
    [DbContext(typeof(PlantDbContext))]
    [Migration("20260903120000_AddPlantSourceSpeciesLinks")]
    partial class AddPlantSourceSpeciesLinks
    {
    }
}
