// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Midnight.EC.Plant.WEB.Models.Data;

#nullable disable

namespace Midnight.EC.Plant.WEB.Models.Migrations
{
    [DbContext(typeof(PlantDbContext))]
    [Migration("20260831135624_AddPlantProfileAndReminders")]
    partial class AddPlantProfileAndReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NickName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisScope")
                        .HasColumnType("int");

                    b.Property<int>("AnalysisType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiaryId")
                        .HasColumnType("int");

                    b.Property<int?>("HealthScore")
                        .HasColumnType("int");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.HasIndex("PlantId", "CreatedAt");

                    b.ToTable("PlantAnalyses", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysisJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("int");

                    b.Property<int>("AnalysisScope")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiaryId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique()
                        .HasFilter("[AnalysisId] IS NOT NULL");

                    b.HasIndex("DiaryId");

                    b.HasIndex("PlantId");

                    b.HasIndex("Status");

                    b.ToTable("PlantAnalysisJobs", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantCareRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CareType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CareType");

                    b.HasIndex("PlantId", "RecordDate");

                    b.ToTable("PlantCareRecords", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiaryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FertilizerNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WateringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeatherNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "DiaryDate");

                    b.ToTable("PlantDiaries", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaryId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.ToTable("PlantImages", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataVersion")
                        .HasColumnType("int");

                    b.Property<string>("DiseaseProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dormancy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FertilizerRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrowthSeason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HumidityRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LightRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PestProblems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepottingAdvice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoilRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SourceUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TemperatureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WaterRequirement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId")
                        .IsUnique();

                    b.ToTable("PlantKnowledge", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantKnowledgeSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ResponseHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PlantKnowledgeSyncLogs", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FertilizingIntervalDays")
                        .HasColumnType("int");

                    b.Property<string>("PersonalCareNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetHumidityMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TargetHumidityMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TargetTemperatureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TargetTemperatureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WateringIntervalDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("PlantProfiles", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ReminderType")
                        .HasColumnType("int");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("PlantId", "SourceKey")
                        .IsUnique();

                    b.HasIndex("PlantId", "Status");

                    b.ToTable("PlantReminders", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReliabilityLevel")
                        .HasColumnType("int");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("Url");

                    b.ToTable("PlantSources", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSourceContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CleanText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParserType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ParserVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SourceId");

                    b.ToTable("PlantSourceContents", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChineseName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CommonName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Genus")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaxonId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChineseName");

                    b.HasIndex("CommonName");

                    b.HasIndex("ScientificName");

                    b.HasIndex("TaxonId");

                    b.ToTable("PlantSpecies", (string)null);
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.Plant", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", "Species")
                        .WithMany("Plants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysis", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", "Diary")
                        .WithMany("Analyses")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithMany("Analyses")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diary");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysisJob", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysis", "Analysis")
                        .WithOne("Job")
                        .HasForeignKey("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysisJob", "AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", "Diary")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithMany("AnalysisJobs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Diary");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantCareRecord", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithMany("CareRecords")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithMany("Diaries")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantImage", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", "Diary")
                        .WithMany("Images")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantKnowledge", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", "Species")
                        .WithOne("Knowledge")
                        .HasForeignKey("Midnight.EC.Plant.WEB.Models.Entities.PlantKnowledge", "SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantKnowledgeSyncLog", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", "Species")
                        .WithMany("SyncLogs")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantProfile", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithOne("Profile")
                        .HasForeignKey("Midnight.EC.Plant.WEB.Models.Entities.PlantProfile", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantReminder", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.Plant", "Plant")
                        .WithMany("Reminders")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSource", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", "Species")
                        .WithMany("Sources")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSourceContent", b =>
                {
                    b.HasOne("Midnight.EC.Plant.WEB.Models.Entities.PlantSource", "Source")
                        .WithMany("Contents")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.Plant", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("AnalysisJobs");

                    b.Navigation("CareRecords");

                    b.Navigation("Diaries");

                    b.Navigation("Profile");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantAnalysis", b =>
                {
                    b.Navigation("Job");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantDiary", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("AnalysisJobs");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSource", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Midnight.EC.Plant.WEB.Models.Entities.PlantSpecies", b =>
                {
                    b.Navigation("Knowledge");

                    b.Navigation("Plants");

                    b.Navigation("Sources");

                    b.Navigation("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
